baseURL = "http://localhost:8080/"
languageCode = "en-us"
title = "Hugo Admin Site"
theme = "ananke"
defaultContentLanguage = "en"
enableRobotsTXT = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.zh]
    weight = 2
    languageName = "中文"
