baseURL = "http://localhost:8080/"
title = "Hugo Admin Site"
theme = "paper"
markup.goldmark.renderer.unsafe = true
[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light